Repository windingtree/lpms-server, pull requests merged in 2022-06, with the labels that each got.

#4 CI/CD test environment
  .github/workflows/release.yml
Labels: A-releases, D-easy, T-bug

#14 feat: all database implementation from schema
  src/controllers/FacilityController.ts
  src/repositories/SpaceAvailabilityRepository.ts
  src/services/DBService.ts
Labels: D-chore

#27 Feat/rates connectors
  package.json
  src/controllers/FacilityController.ts
  src/exceptions/ApiError.ts
  src/repositories/FacilityModifierRepository.ts
  src/repositories/FacilityRepository.ts
  src/repositories/ItemModifierRegistry.ts
  src/repositories/StubRepository.ts
  src/router/index.ts
  src/services/DBService.ts
  yarn.lock
Labels: D-average, P-high, T-feature, C-lpms-server

#28 feat: rules repository
  src/repositories/RuleRepository.ts
  src/services/DBService.ts
  test/repository.spec.ts
Labels: D-average, P-high, C-database

#48 docs: Services
  docs/SERVICES.md
Labels: A-docs

#51 Videre PingPong Service
  package.json
  src/config.ts
  src/index.ts
  src/services/PingPongService.ts
  src/services/WakuService.ts
  yarn.lock
Labels: D-easy, C-waku

#65 fix: 🐛 videre config variables
  .env.example
  src/config.ts
Labels: D-chore

#72 Guard protobuf message decoding and EIP-712 signing
  src/controllers/StorageController.ts
  src/services/AuctioneerService.ts
  src/services/PingPongService.ts
  src/services/WakuService.ts
Labels: T-bug, C-waku

#68 Feat/facility api
  package.json
  src/config.ts
  src/controllers/FacilityController.ts
  src/controllers/FacilityItemController.ts
  src/repositories/FacilityRepository.ts
  src/router/index.ts
  src/rules/Bytes32StringRules.ts
  src/services/FacilityService.ts
  src/services/PingPongService.ts
  src/services/StubService.ts
  src/services/WalletService.ts
  src/utils.ts
  test/api.spec.ts
  test/common.ts
  test/sign.ts
  test/spaceSearch.spec.ts
  yarn.lock
Labels: C-database, C-api

#80 fix: config breakage and stringify
  package.json
  src/services/AuctioneerService.ts
  src/services/IpfsService.ts
  src/services/PingPongService.ts
Labels: D-easy, T-bug
